/**
 * Monomorphic Ventricular Tachycardia (VT).
 *
 * A fast, regular, wide-complex rhythm originating below the AV node. There
 * is no organized atrial activity (no P wave) and the QRS is generated by
 * slow cell-to-cell ventricular conduction rather than the His-Purkinje
 * system, producing a wide, bizarre complex (>120 ms) with the T wave
 * deflecting opposite the dominant QRS polarity (discordant repolarization).
 * Sustained monomorphic VT is poorly perfusing.
 */

import { jitterBeat } from "../waveform.js";
import { randRange } from "./util.js";

/**
 * Build a Monomorphic Ventricular Tachycardia rhythm generator.
 *
 * @param {Object} [opts]
 * @param {number} [opts.rate] Ventricular rate in bpm (default random 150-210).
 * @returns {import("../rhythm.js").Rhythm} A stateful VT rhythm.
 */
export function createVT(opts = {}) {
  const rate = opts.rate ?? randRange(150, 210);
  const meanRR = 60 / rate;

  // Monomorphic = one fixed morphology beat after beat. The dominant QRS is
  // upright in the monitored Lead II so the wide complex is detectable as a
  // positive R peak; the T wave is discordant (opposite sign to the QRS).
  const rAmp = randRange(1.2, 1.8);
  const rSigma = randRange(0.045, 0.06);
  const tAmp = -randRange(0.3, 0.4);
  const tOffset = randRange(0.24, 0.3);

  /** @type {import("../waveform.js").Wave[]} */
  const vtBeat = [
    // Small opposite pre-deflection, exaggerating the bizarre wide onset.
    { name: "Q", offset: -0.03, amp: -randRange(0.1, 0.2), sigma: 0.02 },
    // Wide, tall monophasic R (the wide, bizarre ventricular complex).
    { name: "R", offset: 0.0, amp: rAmp, sigma: rSigma },
    // Discordant T wave, opposite polarity to the QRS.
    { name: "T", offset: tOffset, amp: tAmp, sigma: 0.07 },
  ];

  let lastR = null;

  return {
    name: "Monomorphic Ventricular Tachycardia",
    label: "VT",
    critical: true,
    vitals: {
      sys: Math.round(randRange(80, 92)),
      dia: Math.round(randRange(55, 65)),
      spo2: Math.round(randRange(88, 93)),
    },
    nextBeat() {
      if (lastR === null) {
        lastR = 0;
      } else {
        // Tight, regular R-R with only trivial jitter (<2%) — VT is regular.
        lastR += meanRR * (1 + (Math.random() * 2 - 1) * 0.015);
      }
      return { tR: lastR, waves: jitterBeat(vtBeat), isVentricular: true };
    },
  };
}
